import React, {useState} from 'react'

function mdFromSchedule(meta, schedule){
  let md = `# Study Plan\n\n`;
  md += `Generated by Study Planner\n\n`;
  md += `**Days**: ${meta.days}  \n**Sessions/day**: ${meta.sessions_per_day}  \n**Minutes/session**: ${meta.minutes_per_session}  \n\n`;
  for(const day of Object.keys(schedule)){
    md += `## ${day}\n\n`;
    schedule[day].forEach(s => {
      md += `- **${s.type}** — ${s.topic} (${s.duration_minutes} min)\n  - ${s.notes || ''}\n`;
    })
    md += `\n`;
  }
  return md;
}

function localGenerate(topics, days, sessionsPerDay, minutesPerSession){
  const schedule = {}
  const normalizedTopics = topics.length ? topics : ['Study']

  for(let day = 1; day <= days; day++){
    const dayKey = `Day ${day}`
    schedule[dayKey] = []
    for(let session = 0; session < sessionsPerDay; session++){
      const topic = normalizedTopics[(day - 1 + session) % normalizedTopics.length]
      const isReview = day > 2 && (day % 3 === 0)
      schedule[dayKey].push({
        session_number: (day - 1) * sessionsPerDay + session + 1,
        topic,
        type: isReview ? 'Review' : 'Learn',
        duration_minutes: minutesPerSession,
        notes: isReview
          ? `Review key concepts and practice problems for ${topic}.`
          : `Focus on core concepts and active practice for ${topic}.`,
      })
    }
    if(day % 4 === 0){
      const reviewTopic = normalizedTopics[(day - 1) % normalizedTopics.length]
      schedule[dayKey].push({
        session_number: null,
        topic: reviewTopic,
        type: 'Review',
        duration_minutes: Math.max(10, Math.floor(minutesPerSession / 2)),
        notes: `Quick spaced repetition review for ${reviewTopic}.`,
      })
    }
  }

  return {
    meta: {days, sessions_per_day: sessionsPerDay, minutes_per_session: minutesPerSession, source: 'browser'},
    schedule,
  }
}

export default function App(){
  const [topicsText, setTopicsText] = useState('Algorithms\nData Structures\nSystem Design')
  const [days, setDays] = useState(7)
  const [spd, setSpd] = useState(1)
  const [mins, setMins] = useState(30)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [data, setData] = useState(null)

  async function generate(){
    setLoading(true); setError(null); setData(null)
    const topics = topicsText.split(/[\n,]+/).map(s=>s.trim()).filter(Boolean)
    try{
      const result = localGenerate(topics, Number(days), Number(spd), Number(mins))
      await new Promise(resolve => setTimeout(resolve, 120))
      setData(result)
    }catch(e){
      setError('Unable to generate study plan. Please check your inputs.')
    }finally{setLoading(false)}
  }

  function downloadMarkdown(){
    if(!data) return
    const md = mdFromSchedule(data.meta, data.schedule)
    const blob = new Blob([md], {type:'text/markdown'})
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = 'study-plan.md'; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url)
  }

  return (
    <div className="container">
      <header>
        <h1>Study Planner</h1>
        <p className="muted">Fast MVP: generate a multi-day study schedule with spaced repetition.</p>
      </header>

      <main>
        <section className="card form">
          <label>Topics</label>
          <textarea value={topicsText} onChange={e=>setTopicsText(e.target.value)} />
          <div className="row">
            <label>Days <input type="number" value={days} min={1} onChange={e=>setDays(e.target.value)} /></label>
            <label>Sessions/day <input type="number" value={spd} min={1} onChange={e=>setSpd(e.target.value)} /></label>
            <label>Minutes/session <input type="number" value={mins} min={5} onChange={e=>setMins(e.target.value)} /></label>
          </div>
          <div className="actions">
            <button onClick={generate} className="primary" disabled={loading}>{loading? 'Generating...':'Generate Plan'}</button>
            <button onClick={()=>{setTopicsText('')}}>Clear</button>
            <button onClick={downloadMarkdown} disabled={!data}>Download Markdown</button>
          </div>
          {error && <div className="error">{error}</div>}
        </section>

        <section className="card result">
          {!data && <div className="placeholder">Your generated plan will appear here.</div>}
          {data && (
            <div>
              <div className="meta">Source: {data.meta?.source || 'unknown'}</div>
              <div className="grid">
                {Object.keys(data.schedule).map(day => (
                  <article key={day} className="day">
                    <h3>{day}</h3>
                    {data.schedule[day].map((s, i) => (
                      <div key={i} className={`session ${s.type.toLowerCase()}`}>
                        <div className="session-head">
                          <strong>{s.topic}</strong>
                          <span className="badge">{s.type}</span>
                        </div>
                        <div className="session-meta">{s.duration_minutes} min</div>
                        <div className="session-notes">{s.notes}</div>
                      </div>
                    ))}
                  </article>
                ))}
              </div>
            </div>
          )}
        </section>
      </main>

      <footer>
        <small>Hack Days Delhi — Study Planner MVP</small>
      </footer>
    </div>
  )
}
